local mock = require("spec.support.mock_nk")

describe("mock_nk", function()
  it("拦截 require('nakama')", function()
    local calls = mock.install()
    require("nakama").logger_info("hi")
    assert.same({ "hi" }, calls.logs)
  end)

  it("json 往返", function()
    mock.install()
    local nk = require("nakama")
    assert.equal(1, nk.json_decode(nk.json_encode({ a = 1 })).a)
  end)

  it("dispatcher 记录广播与 label", function()
    local d = mock.dispatcher()
    d.broadcast_message(30, '{"x":1}')
    d.match_label_update('{"g":"rps"}')
    assert.equal(30, d.broadcasts[1].op)
    assert.equal('{"g":"rps"}', d.labels[1])
  end)

  it("last() 取回最后一条指定 op 的广播", function()
    local d = mock.dispatcher()
    d.broadcast_message(10, '{"n":1}')
    d.broadcast_message(10, '{"n":2}')
    assert.equal(2, mock.last(d, 10).n)
  end)
end)
